name: Actualizar Precios DLR

on:
  schedule:
    # Horario: 10:30 a 17:00 ART (UTC-3) => 13:30 a 20:00 UTC. Lunes a Viernes (1-5).
    - cron: '30-59/20 13 * * 1-5'  # 13:30, 13:50 UTC
    - cron: '*/20 14-19 * * 1-5'   # 14:00 a 19:40 UTC
    - cron: '0 20 * * 1-5'         # 20:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pyRofex python-dotenv

      - name: Run script
        env:
          PRIMARY_USER: ${{ secrets.PRIMARY_USER }}
          PRIMARY_PASSWORD: ${{ secrets.PRIMARY_PASSWORD }}
          PRIMARY_ACCOUNT: ${{ secrets.PRIMARY_ACCOUNT }}
        run: python get_prices_once.py

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add curva_dlr.json
          git commit -m "Auto-update prices: $(date)" || exit 0
          git push
